version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.002
    image: railsapp:redis
    ports:
      - "3000:3000"
    volumes:
    - .:/usr/src/app/
    environment:
      REDIS_HOST: redis 
  redis:
    image: redis
