version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.002
    image: 'railsapp:withdb'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      REDIS_HOST: redis
    env_file:
      - .env/development/database
      - .env/development/web      
  redis:
    image: redis
  mysqldb:
    image: 'mysql:5.7'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    env_file:
      - .env/development/database
    volumes:
      - mysqldb_data:/var/lib/mysql
volumes:
    mysqldb_data:

